# 2025 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)

{
    "name": "Bundle common accounting modules",
    "summary": "Install at once all common modules related to the accounting.",
    "version": "16.0.1.0.0",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "category": "Hidden",
    "application": False,
    "installable": True,
    "depends": [
        "account",
        "account_asset_management",
        "account_banking_mandate",
        "account_banking_pain_base",
        "account_banking_sepa_credit_transfer",
        "account_banking_sepa_direct_debit",
        "account_chart_update",
        "account_credit_control",
        "account_due_list",
        "account_edi",
        "account_edi_ubl_cii",
        "account_financial_report",
        "account_lock_date_update",
        "account_payment",
        "account_payment_invoice_online_payment_patch",
        "account_payment_mode",
        "account_payment_order",
        "account_payment_order_return",
        "account_payment_partner",
        "account_payment_purchase",
        "account_payment_return",
        "account_payment_return_import",
        "account_payment_sale",
        "account_reconcile_oca",
        "account_sequence",
        "account_statement_base",
        "account_statement_import_base",
        "account_statement_import_file",
        "account_statement_import_file_reconcile_oca",
        "account_statement_import_online",
        "account_statement_import_online_gocardless",
        "account_tax_balance",
        "analytic",
        "base_bank_from_iban",
        "base_vat",
        "l10n_es",
        "l10n_es_account_asset",
        "l10n_es_account_statement_import_n43",
        "l10n_es_aeat",
        "l10n_es_aeat_mod111",
        "l10n_es_aeat_mod115",
        "l10n_es_aeat_mod347",
        "l10n_es_mis_report",
        "l10n_es_partner",
        "l10n_es_partner_mercantil",
        "mis_builder",
        "mis_builder_budget",
        "partner_vat_unique",
        "payment",
    ],
    "data": [
    ],
}
