# -*- coding: utf-8 -*-
# 2026 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import models, fields, api


class BaseConfigSettings(models.TransientModel):
    _inherit = "base.config.settings"

    partner_child_portal = fields.Boolean(
        string="Partner child portal access",
        default=False,
        help="If checked, child partners will be granted portal access "
             "instead of res.partner."
    )

    portal_login_from_vat = fields.Boolean(
        string="Portal login from NIF/DNI",
        default=False,
        help="If checked, the autogenerated portal login for contacts "
             "without email is built from the NIF/DNI (with the check "
             "letter in lowercase) instead of the partner code."
    )

    keep_partner_email_on_user_change = fields.Boolean(
        string="Keep partner email on user change",
        default=False,
        help="If checked, changing the email of a portal user will not "
             "overwrite the real email stored on the linked partner."
    )

    @api.model
    def get_default_partner_child_portal(self, fields_list):
        value = self.env['ir.values'].sudo().get_default(
            'base.config.settings', 'partner_child_portal')
        return {
            'partner_child_portal': value if value is not None else False,
        }

    @api.model
    def get_default_portal_login_from_vat(self, fields_list):
        value = self.env['ir.values'].sudo().get_default(
            'base.config.settings', 'portal_login_from_vat')
        return {
            'portal_login_from_vat': value if value is not None else False,
        }

    @api.model
    def get_default_keep_partner_email_on_user_change(self, fields_list):
        value = self.env['ir.values'].sudo().get_default(
            'base.config.settings', 'keep_partner_email_on_user_change')
        return {
            'keep_partner_email_on_user_change':
                value if value is not None else False,
        }

    @api.multi
    def set_default_values(self):
        res = None
        parent = super(BaseConfigSettings, self)
        if hasattr(parent, 'set_default_values'):
            res = parent.set_default_values()
        values = self.env['ir.values'].sudo()
        values.set_default('base.config.settings', 'partner_child_portal',
                           self.partner_child_portal)
        values.set_default('base.config.settings', 'portal_login_from_vat',
                           self.portal_login_from_vat)
        values.set_default('base.config.settings',
                           'keep_partner_email_on_user_change',
                           self.keep_partner_email_on_user_change)
        return res
