{
 "title": "Welcome Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "FuenteDatos", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Censo y Parcelario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Partners activos\" FROM res_partner WHERE active;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Usuarios\" FROM res_users WHERE is_wua_user AND active;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Usuarios de portal\" FROM res_users WHERE is_wua_portal_user AND active;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Proveedores\" FROM res_partner WHERE supplier AND active;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Partners inactivos\" FROM res_partner WHERE active = false;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Socios\" FROM res_partner WHERE active AND is_wua_partner;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Propietarios\" FROM res_partner WHERE active AND is_wua_partner AND is_owner;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Arrendatarios\" FROM res_partner WHERE active AND is_wua_partner AND is_lessee;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Parcelas\" FROM wua_parcel WHERE active;\n"
    },
    {
     "rawSql": "SELECT count(*) AS \"Arrendadas\" FROM (SELECT distinct parcel_id FROM wua_parcel_partnerlink WHERE active AND profile = 'L') leased_parcels;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Sin propietario\" FROM wua_parcel WHERE partner_id IS NULL;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Subparcelas\" FROM wua_parcel_subparcel WHERE active;"
    },
    {
     "rawSql": "SELECT count(*) AS \"Inactivas\" FROM wua_parcel WHERE active = false;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Ha" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(area_official) AS \"Superficie total censada\" FROM wua_parcel WHERE active;\n"
    },
    {
     "rawSql": "    SELECT sum(p.area_official) AS \"Superficie total arrendada\"\n      FROM (SELECT distinct parcel_id FROM wua_parcel_partnerlink WHERE active and profile = 'L') l\nINNER JOIN wua_parcel p ON l.parcel_id=p.id;\n\n"
    }
   ]
  },
  { "title": "Territorio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Área por sector hidráulico",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ha" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wh1.name AS \"Sector hidráulico\", sum(wp1.area_official) AS \"Área total\"\nFROM wua_parcel wp1\nINNER JOIN wua_hydraulicsector wh1 ON wp1.hydraulicsector_id = wh1.id\nGROUP BY \"Sector hidráulico\"\nORDER BY \"Sector hidráulico\"\n"
    }
   ]
  },
  { "title": "Base de datos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Tamaño base de datos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size(pg_database.datname) FROM pg_database WHERE pg_database.datname = current_database();"
    }
   ]
  },
  {
   "title": "Módulos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) AS \"Instalados\" FROM ir_module_module WHERE state = 'installed';"
    },
    {
     "rawSql": "SELECT count(id) AS \"No instalados\" FROM ir_module_module WHERE state = 'uninstalled';"
    },
    {
     "rawSql": "SELECT count(id) AS \"No instalables\" FROM ir_module_module WHERE state = 'uninstallable';"
    }
   ]
  }
 ]
}