# 2026 Moval Agroingeniería
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

{
    "name": "Base Assembly",
    "summary": "Core models for assemblies: agenda, attendees, delegations, voting",
    "version": "18.0.1.0.1",
    "category": "Administration",
    "author": "Moval Agroingeniería",
    "website": "https://www.moval.es",
    "license": "AGPL-3",
    "depends": [
        "base",
        "base_address_extended",
        "base_setup",
        "base_vat",
        "base_vote",
        "link_tracker",
        "mail",
        "web",
    ],
    "post_init_hook": "post_init_hook",
    "assets": {
        "web.assets_backend": [
            "base_assembly/static/src/js/document_preview_wizard_form.js",
        ],
    },
    "data": [
        "security/assembly_security.xml",
        "security/assembly_security_multicompany_sync.xml",
        "security/assembly_group_system.xml",
        "security/ir.model.access.csv",
        "data/assembly_sequence_data.xml",
        "data/assembly_mail_templates.xml",
        "data/assembly_af_render_fallback_views.xml",
        "data/assembly_attendance_http_templates.xml",
        "views/assembly_type_views.xml",
        "views/assembly_assembly_views.xml",
        "views/assembly_attendee_views.xml",
        "views/assembly_delegation_views.xml",
        "views/assembly_representation_views.xml",
        "views/assembly_agenda_option_views.xml",
        "views/assembly_assembly_header_actions_wizard_views.xml",
        "views/assembly_document_preview_wizard_views.xml",
        "views/assembly_communication_send_wizard_views.xml",
        "views/assembly_ballot_print_wizard_views.xml",
        "views/assembly_voting_views.xml",
        "views/assembly_voting_session_views.xml",
        "views/assembly_agenda_session_views.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
        "report/assembly_report_snippets.xml",
        "report/assembly_attendance_reports_data.xml",
        "report/assembly_attendance_reports_templates.xml",
        "report/assembly_delegation_report_data.xml",
        "report/assembly_delegation_report_templates.xml",
        "report/assembly_representation_report_data.xml",
        "report/assembly_representation_report_templates.xml",
        "report/assembly_voting_ballot_reports_data.xml",
        "report/assembly_voting_ballot_reports_templates.xml",
        "report/assembly_publication_document_report_data.xml",
        "report/assembly_publication_document_report_templates.xml",
        "data/assembly_cleanup_delegation_views.xml",
    ],
}
